kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bob-rolebinding
  annotations:
    configmanagement.gke.io/cluster-selector: selector-env-prod
subjects:
- kind: User
  name: bob@acme.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: acme-admin
  apiGroup: rbac.authorization.k8s.io

